-- Adequacao de USER_SECURITY_PROFILE para vinculos de usuario em producao
-- Executar com usuario com privilegio para ALTER no schema DJANGO_API e GRANT nos schemas origem.

GRANT SELECT, REFERENCES ON SIAOS.USUARIO TO DJANGO_API;

ALTER TABLE DJANGO_API.USER_SECURITY_PROFILE
  ADD (
    USU_CHAPA NUMBER(5)
  );

ALTER TABLE DJANGO_API.USER_SECURITY_PROFILE
  ADD CONSTRAINT FK_USP_AUTH_USER
  FOREIGN KEY (USER_ID)
  REFERENCES DJANGO_API.AUTH_USER (ID);

ALTER TABLE DJANGO_API.USER_SECURITY_PROFILE
  ADD CONSTRAINT FK_USP_USU_CHAPA
  FOREIGN KEY (USU_CHAPA)
  REFERENCES SIAOS.USUARIO (USU_CHAPA);
