services:
    web:
        build: .
        container_name: smar-license-api
        working_dir: /app/backend
        ports:
            - "8000:8000"
        env_file:
            - backend/.env
        environment:
            - ORACLE_HOME=/opt/oracle/instantclient_19_25
            - LD_LIBRARY_PATH=/opt/oracle/instantclient_19_25
            - ORACLE_CLIENT_PATH=/opt/oracle/instantclient_19_25
        extra_hosts:
            - "dbdesenv:192.168.1.168"
        volumes:
            - .:/app
        command:
            - sh
            - -c
            - python manage.py collectstatic --noinput && exec gunicorn --reload --bind 0.0.0.0:8000 config.wsgi:application
        restart: unless-stopped

    frontend:
        build:
            context: .
            dockerfile: frontend/Dockerfile
            args:
                VITE_DJANGO_API_URL: http://localhost:8000/api
                VITE_APP_RUNTIME_ENV: development
        container_name: smar-license-frontend
        ports:
            - "3000:8080"
        restart: unless-stopped
