# Generated by Django 5.2.6 on 2026-08-08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_infrastructure", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersecurityprofile",
            name="emp_codigo",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usersecurityprofile",
            name="pes_numero",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
