# Generated by Django 5.2.14 on 2026-06-17 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                (
                    "token_prefix",
                    models.CharField(
                        help_text="Primeiros caracteres do token, só para exibição/identificação na UI",
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Ativo"), ("revoked", "Revogado")],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Nome livre, ex: 'Notebook do caixa 2'",
                        max_length=100,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Gerente dono deste token",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tokens_revoked",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_uuid", models.CharField(db_index=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Ativo"), ("revoked", "Revogado")],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("last_access_at", models.DateTimeField(blank=True, null=True)),
                ("last_access_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "token",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="machine",
                        to="branch_auth_infrastructure.accesstoken",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TokenAccessAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_uuid_sent", models.CharField(max_length=64)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("success", "Sucesso"),
                            ("invalid_token", "Token inválido"),
                            ("revoked_token", "Token revogado"),
                            ("device_mismatch", "Device UUID divergente"),
                            ("machine_revoked", "Máquina revogada"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "token",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_attempts",
                        to="branch_auth_infrastructure.accesstoken",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="tokenaccessattempt",
            index=models.Index(
                fields=["token", "created_at"], name="branch_auth_token_i_d99460_idx"
            ),
        ),
    ]
