-- Grants Oracle — Follow-up / Recado (Smarnet Novo, usuário API_SMAR)
-- Aplicar como DBA. Tabelas já existem — não rodar DDL de CREATE aqui.
-- Documentação: docs/admins/grants-oracle-followup.md

GRANT SELECT ON SIAOS.PROP_RECADO TO API_SMAR;
GRANT SELECT ON SIAOS.TIPO_RECADO TO API_SMAR;
GRANT SELECT ON SIAOS.MOTIVO TO API_SMAR;
GRANT SELECT ON SIAOS.FOLLOW_CLIENTE TO API_SMAR;
GRANT EXECUTE ON SIAOS.SP_UPDATE_FOLLOWUP TO API_SMAR;

-- Já devem existir (não repetir se já aplicados):
-- GRANT EXECUTE ON SIAOS.PCK_SMART_SALES3 TO API_SMAR;
-- GRANT SELECT ON SIAOS.USUARIO TO API_SMAR;
-- GRANT SELECT ON SMARNET.LEGENDA TO API_SMAR;
-- GRANT SELECT ON SMARNET.LEGENDA_TEXTO TO API_SMAR;
