"""Administracao API URL configuration."""

from django.urls import path

from apps.commercial.presentation.views.cliente_dashboard_views import (
    ClienteDashboardCreditoView,
    ClienteDashboardHistoricoOsView,
    ClienteDashboardHistoricoTitulosView,
    ClienteDashboardLimitesView,
)
from apps.commercial.presentation.views.cliente_tab_views import (
    ClienteArclassesView,
    ClienteAreasOsView,
    ClienteArlevelsView,
    ClienteArsalespsView,
    ClienteBloqueioView,
    ClienteCidadesView,
    ClienteCobrancaPadraoView,
    ClienteCobrancasView,
    ClienteContatoPadraoView,
    ClienteContatosView,
    ClienteEmbarquePadraoView,
    ClienteEmbarquesView,
    ClienteFinanceiroView,
    ClienteGruposTributariosView,
    ClienteLogsView,
    ClienteModelosPagtoView,
    ClienteObsView,
    ClienteRiscosView,
)
from apps.commercial.presentation.views.cliente_views import (
    ClienteCnpjConsultaView,
    ClienteCollectionView,
    ClienteDetailView,
    ClienteDocumentoLookupView,
    ClienteEstadosView,
    ClienteFromFuncionarioView,
    ClienteFuncionarioConsultaView,
    ClienteOrigensView,
    ClientePaisesView,
)

urlpatterns = [
    path("clientes/", ClienteCollectionView.as_view(), name="administracao-clientes"),
    path(
        "clientes/documento/",
        ClienteDocumentoLookupView.as_view(),
        name="administracao-cliente-documento",
    ),
    path(
        "clientes/cnpj/",
        ClienteCnpjConsultaView.as_view(),
        name="administracao-cliente-cnpj",
    ),
    path(
        "clientes/funcionario/",
        ClienteFuncionarioConsultaView.as_view(),
        name="administracao-cliente-funcionario",
    ),
    path(
        "clientes/from-funcionario/",
        ClienteFromFuncionarioView.as_view(),
        name="administracao-cliente-from-funcionario",
    ),
    path(
        "clientes/<int:codigo>/",
        ClienteDetailView.as_view(),
        name="administracao-cliente-detail",
    ),
    path(
        "clientes/<int:codigo>/financeiro/",
        ClienteFinanceiroView.as_view(),
        name="administracao-cliente-financeiro",
    ),
    path(
        "clientes/<int:codigo>/contatos/",
        ClienteContatosView.as_view(),
        name="administracao-cliente-contatos",
    ),
    path(
        "clientes/<int:codigo>/contatos/padrao/",
        ClienteContatoPadraoView.as_view(),
        name="administracao-cliente-contato-padrao",
    ),
    path(
        "clientes/<int:codigo>/cobrancas/",
        ClienteCobrancasView.as_view(),
        name="administracao-cliente-cobrancas",
    ),
    path(
        "clientes/<int:codigo>/cobrancas/padrao/",
        ClienteCobrancaPadraoView.as_view(),
        name="administracao-cliente-cobranca-padrao",
    ),
    path(
        "clientes/<int:codigo>/embarques/",
        ClienteEmbarquesView.as_view(),
        name="administracao-cliente-embarques",
    ),
    path(
        "clientes/<int:codigo>/embarques/padrao/",
        ClienteEmbarquePadraoView.as_view(),
        name="administracao-cliente-embarque-padrao",
    ),
    path(
        "clientes/<int:codigo>/logs/",
        ClienteLogsView.as_view(),
        name="administracao-cliente-logs",
    ),
    path(
        "clientes/<int:codigo>/observa/",
        ClienteObsView.as_view(),
        name="administracao-cliente-observa",
    ),
    path(
        "clientes/<int:codigo>/bloqueio/",
        ClienteBloqueioView.as_view(),
        name="administracao-cliente-bloqueio",
    ),
    path(
        "clientes/<int:codigo>/dashboard/credito/",
        ClienteDashboardCreditoView.as_view(),
        name="administracao-cliente-dashboard-credito",
    ),
    path(
        "clientes/<int:codigo>/dashboard/limites/",
        ClienteDashboardLimitesView.as_view(),
        name="administracao-cliente-dashboard-limites",
    ),
    path(
        "clientes/<int:codigo>/dashboard/historico/os/",
        ClienteDashboardHistoricoOsView.as_view(),
        name="administracao-cliente-dashboard-historico-os",
    ),
    path(
        "clientes/<int:codigo>/dashboard/historico/titulos/",
        ClienteDashboardHistoricoTitulosView.as_view(),
        name="administracao-cliente-dashboard-historico-titulos",
    ),
    path(
        "catalogos/paises/",
        ClientePaisesView.as_view(),
        name="administracao-catalogos-paises",
    ),
    path(
        "catalogos/estados/",
        ClienteEstadosView.as_view(),
        name="administracao-catalogos-estados",
    ),
    path(
        "catalogos/origens/",
        ClienteOrigensView.as_view(),
        name="administracao-catalogos-origens",
    ),
    path(
        "catalogos/arclasses/",
        ClienteArclassesView.as_view(),
        name="administracao-catalogos-arclasses",
    ),
    path(
        "catalogos/arlevels/",
        ClienteArlevelsView.as_view(),
        name="administracao-catalogos-arlevels",
    ),
    path(
        "catalogos/arsalesps/",
        ClienteArsalespsView.as_view(),
        name="administracao-catalogos-arsalesps",
    ),
    path(
        "catalogos/cidades/",
        ClienteCidadesView.as_view(),
        name="administracao-catalogos-cidades",
    ),
    path(
        "catalogos/grupos-tributarios/",
        ClienteGruposTributariosView.as_view(),
        name="administracao-catalogos-grupos-tributarios",
    ),
    path(
        "catalogos/areas-os/",
        ClienteAreasOsView.as_view(),
        name="administracao-catalogos-areas-os",
    ),
    path(
        "catalogos/modelos-pagto/",
        ClienteModelosPagtoView.as_view(),
        name="administracao-catalogos-modelos-pagto",
    ),
    path(
        "catalogos/riscos-cliente/",
        ClienteRiscosView.as_view(),
        name="administracao-catalogos-riscos-cliente",
    ),
]
