-- Compilar como SIAOS (API_SMAR toma ORA-01031).
-- PK + PRE_DATA; default PRE_SISTEMA=121 só quando PRP_CODIGO vem preenchido.

CREATE OR REPLACE TRIGGER SIAOS.TG_B_I_PROP_RECADO
BEFORE INSERT ON PROP_RECADO FOR EACH ROW
DECLARE
   pre_cod        SIAOS.PROP_RECADO.PRE_CODIGO%TYPE;
BEGIN
   SELECT SIAOS.SQ_PROP_RECADO.NEXTVAL
     INTO pre_cod
     FROM DUAL;
   :NEW.PRE_CODIGO := pre_cod;
   :NEW.PRE_DATA := SYSDATE;
   IF :NEW.PRP_CODIGO IS NOT NULL AND :NEW.PRE_SISTEMA IS NULL THEN
     :NEW.PRE_SISTEMA := 121;
     :NEW.PRE_FILTRO := :NEW.PRP_CODIGO;
   END IF;
END;
/
