-- Compilar como SIAOS.
-- Baixa pendência via PCK_PENDENCIA em update/delete.

CREATE OR REPLACE TRIGGER SIAOS.TG_B_U_PROP_RECADO
BEFORE UPDATE OR DELETE ON PROP_RECADO FOR EACH ROW
BEGIN
   IF UPDATING THEN
     IF :OLD.PRE_DT_BAIXA IS NOT NULL AND :OLD.PNU_NUMERO IS NOT NULL THEN
        SIAOS.PCK_PENDENCIA.SP_UP_BAIXA_PEN(n_pnu_numero => :NEW.PNU_NUMERO ,n_pen_numero => :NEW.PEN_NUMERO);
     END IF;
     IF((:OLD.PNU_NUMERO IS NOT NULL)
       AND (:OLD.PRE_DT_BAIXA IS NULL)
       AND (:NEW.PRE_DT_BAIXA IS NOT NULL)) THEN
        SIAOS.PCK_PENDENCIA.SP_UP_BAIXA_PEN(:OLD.PNU_NUMERO, :OLD.PEN_NUMERO);
     END IF;
   ELSIF DELETING THEN
      SIAOS.PCK_PENDENCIA.SP_UP_BAIXA_PEN(n_pnu_numero => :OLD.PNU_NUMERO ,n_pen_numero => :OLD.PEN_NUMERO);
   END IF;
END;
/
