-- Compilar como SIAOS (API_SMAR toma ORA-01031).
-- Pre-requisito: PCK_DQANET.pck (SF_USU_CHAPA_USER).

CREATE OR REPLACE TRIGGER SIAOS.TG_B_I_ARQUIVO BEFORE INSERT ON PROP_ARQUIVO FOR EACH ROW
-- JULIANO BONINI
-- INSERT TRIGGER ON PROP_ARQUIVO

DECLARE
   n_par_cod        SIAOS.PROP_ARQUIVO.PAR_CODIGO%TYPE;
   n_usu_chapa      SIAOS.PROP_ARQUIVO.USU_CHAPA%TYPE;

BEGIN

   BEGIN

     IF :NEW.USU_CHAPA IS NULL THEN
       n_usu_chapa := SIAOS.PCK_DQANET.SF_USU_CHAPA_USER;
       :NEW.USU_CHAPA := n_usu_chapa;
     END IF;

   EXCEPTION WHEN OTHERS THEN
     NULL;
   END;

   IF :NEW.PAR_SISTEMA IS NULL THEN
      IF :NEW.PRP_CODIGO IS NOT NULL THEN
         :NEW.PAR_SISTEMA := 1;
         :NEW.PAR_FILTRO := :NEW.PRP_CODIGO ;
      ELSIF :NEW.ORDER_NO IS NOT NULL THEN
         :NEW.PAR_SISTEMA := 2;
         :NEW.PAR_FILTRO := :NEW.ORDER_NO ;
      END IF;
   END IF;

   SELECT SIAOS.SQ_PROP_ARQUIVO.NEXTVAL
     INTO n_par_cod
     FROM DUAL;

   :NEW.PAR_CODIGO := n_par_cod;
   :NEW.PAR_DATA := SYSDATE;

   BEGIN

     INSERT
       INTO SIAOS.PROP_ARQ_LOG
            (PAR_CODIGO, PAL_DATA, PAL_NOME, USU_CHAPA, PAL_ACAO, PAL_SISTEMA, PAL_FILTRO)
     VALUES (n_par_cod, SYSDATE, :NEW.PAR_NOME, n_usu_chapa, 'INSERT', :NEW.PAR_SISTEMA, :NEW.PAR_FILTRO);

   EXCEPTION WHEN OTHERS THEN
     NULL;
   END;


END;
/
