-- Compilar como SIAOS (API_SMAR toma ORA-01031).
-- Pre-requisito: PCK_DQANET.pck (SF_USU_CHAPA_USER).

CREATE OR REPLACE TRIGGER SIAOS.TG_A_IUD_ARQUIVO
  BEFORE UPDATE OR DELETE ON PROP_ARQUIVO
  FOR EACH ROW
DECLARE

   n_usu_chapa       SIAOS.PROP_ARQUIVO.USU_CHAPA%TYPE;
   n_par_codigo      SIAOS.PROP_ARQUIVO.PAR_CODIGO%TYPE;

BEGIN

 BEGIN
   n_usu_chapa := SIAOS.PCK_DQANET.SF_USU_CHAPA_USER;
  EXCEPTION WHEN OTHERS THEN
    n_usu_chapa := NULL;
  END;

  IF UPDATING THEN

    IF :OLD.PAR_LIXEIRA IS NULL AND :NEW.PAR_LIXEIRA IS NOT NULL THEN

     INSERT
       INTO SIAOS.PROP_ARQ_LOG
            (PAR_CODIGO, PAL_DATA, PAL_NOME, USU_CHAPA, PAL_ACAO, PAL_SISTEMA, PAL_FILTRO)
     VALUES (:OLD.PAR_CODIGO, SYSDATE, :OLD.PAR_NOME, n_usu_chapa, 'DELETE', :OLD.PAR_SISTEMA, :OLD.PAR_FILTRO);

    ELSIF :OLD.PAR_LIXEIRA IS NOT NULL AND :NEW.PAR_LIXEIRA IS NULL THEN

     INSERT
       INTO SIAOS.PROP_ARQ_LOG
            (PAR_CODIGO, PAL_DATA, PAL_NOME, USU_CHAPA, PAL_ACAO, PAL_SISTEMA, PAL_FILTRO)
     VALUES (:OLD.PAR_CODIGO, SYSDATE, :OLD.PAR_NOME, n_usu_chapa, 'RESTORE', :OLD.PAR_SISTEMA, :OLD.PAR_FILTRO);

    ELSE
      IF NVL(:OLD.PAR_CODIGO_PAI,0) != NVL(:NEW.PAR_CODIGO_PAI,0) THEN
         INSERT
           INTO SIAOS.PROP_ARQ_LOG
                (PAR_CODIGO, PAL_DATA, PAL_NOME, USU_CHAPA, PAL_ACAO, PAL_SISTEMA, PAL_FILTRO)
         VALUES (:OLD.PAR_CODIGO, SYSDATE, :OLD.PAR_NOME, n_usu_chapa, 'MOVE', :OLD.PAR_SISTEMA, :OLD.PAR_FILTRO);
       ELSE
         INSERT
           INTO SIAOS.PROP_ARQ_LOG
                (PAR_CODIGO, PAL_DATA, PAL_NOME, USU_CHAPA, PAL_ACAO, PAL_SISTEMA, PAL_FILTRO)
         VALUES (:OLD.PAR_CODIGO, SYSDATE, :OLD.PAR_NOME, n_usu_chapa, 'UPDATE', :OLD.PAR_SISTEMA, :OLD.PAR_FILTRO);
       END IF;
    END IF;

  ELSIF DELETING THEN

     INSERT
       INTO SIAOS.PROP_ARQ_LOG
            (PAR_CODIGO, PAL_DATA, PAL_NOME, USU_CHAPA, PAL_ACAO, PAL_SISTEMA, PAL_FILTRO)
     VALUES (:OLD.PAR_CODIGO, SYSDATE, :OLD.PAR_NOME, n_usu_chapa, 'DELETE', :OLD.PAR_SISTEMA, :OLD.PAR_FILTRO);

  END IF;

END TG_A_IUD_ARQUIVO;
/
