name: CI

on:
    pull_request:
    push:
        branches:
            - master

defaults:
    run:
        working-directory: backend

jobs:
    quality:
        runs-on: ubuntu-latest
        env:
            PYTHONPATH: .

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-python@v5
              with:
                  python-version: "3.13"

            - run: pip install -r requirements/development.txt

            - run: ruff check .

            - run: ruff format --check .

            - run: mypy .

            - run: lint-imports

            - run: pytest
